### ISSUE TITLE
Consider how to handle app-level protocol negotiation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-pairing-channel#29]
I'm spinning this issue out of a discussion I had earlier today with @linuxwolf.

In  a future world where multiple different applications might be doing pairing-style flows based on the same underlying technology, we might find ourselves in a situation where e.g. one end of a pairing channel is expecting to do the FxA OAuth pairing flow, and the other end is expecting to do the devtools remote debugging flow.  I don't believe we currently have any mechanism for detecting and preventing such situations during the handshake. In the best case, such a setup would fail due to parsing/handling errors in the underlying application protocol.  In the worst case, some unfortunate mis-match of expectations might lead to a security vulnerability.

I can think of a couple of ways we might mitigate this.

1. **Push it up the stack**.  For the current FxA pairing flow, the connection is formed by scanning a QR code that contains a URL like "https://accounts.firefox.com/pair#...". The connecting client for the FxA flow is expected to check that this URL matches what its thinks the accounts server is, and bail out if it doesn't.  That'll work for us in the short term, but it would not work in a future world where the user is manually entering a short pairing code rather than scanning a long URL.

2. **Push it down the stack**.  We could require that the underlying application protocol(s) be super careful about validating that the expected flow is taking place.  They should probably do this anyway, but it seems fragile to rely on it.

3. **Use the ALPN extension for TLS.13**.  There is an [application-layer protocol negotiation extension](https://tools.ietf.org/html/rfc7301) for TLS which is designed to achieve basically this - the client can specify the underlying protocol(s) it intends to speak, the server can select one or bail out cleanly, and the exchange is protected by the handshake authentication mechanisms of TLS.  However, the spec says that you can [only use specific pre-registered protocol names](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xml) for this, and I've no idea whether it would be sensible to try to add things in there like "fxa pairing protocol v1" or "Firefox remote debugging protocol" or whatever.

@linuxwolf did you have any further thoughts to share on this topic?

**Comment by rfk** [comment]
Also /cc @martinthomson for any thoughts.

**Comment by martinthomson** [comment]
We've been pushing toward use of ALPN for this sort of thing.  I think that going against the registration policy in RFC 7301 is OK, because it's stupid.  There is a desire in the IETF to loosen the constraints on use of these registries.  I have the TLS chair sitting right next to me, so I'll have a word when I get a chance.

**Comment by rfk** [comment]
> I think that going against the registration policy in RFC 7301 is OK, because it's stupid.

FWIW "Use a collision-resistant name like a URI" was my first thought here, until I discovered that the spec said not to do that.

**Comment by martinthomson** [comment]
I don't think that we need to go there.  "firefox accounts pairing" or something similar is narrow enough to work.  Note that this is also a very good way to get versioning, rather than building any versioning into the protocol itself.  It has the advantage of giving you low latency version negotiation.

**Comment by linuxwolf** [comment]
FWIW, I suggested in an irl chat to consider ALPN; it seemed like a perfect fit.  Looks like it's the right plan to go with.

**Comment by shane-tomlinson** [comment]
@rfk - is this work for train-132 or can it be pushed out? Do you have a rough idea of the "size" for planning?

**Comment by rfk** [comment]
It's a small; I think we should prioitize work on the send-tab infra over this in train-132 though.

**Comment by shane-tomlinson** [comment]
@rfk - for train-133 or can this be put into the backlog?

**Comment by rfk** [comment]
backlog until send-tab stuff is under control

**Comment by rfk** [comment]
Given the issue is now 2 years old, I think it's clear that we're not motivated to do this :-/
