### ISSUE TITLE
Define and publish API for fxa-pairing-tls

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-pairing-channel#3]
We're going to implement a shared JS library containing the crypto pieces for our pairing flow, and import it into both Firefox Desktop and fxa-content-server.  Let's settle on the API to be exposed by this library and publish a stub version of it ASAP, so we can parallelize subsequent work.

Acceptance criteria:
* [ ] Documented public API for fxa-pairing-tls
* [ ] Automated publishing pipeline that is suitable for both Desktop and content-server
* [ ] Initial "dev" version published to facilitate integration work

**Comment by eoger** [comment]
Note from Slack conversion: I'd like the high-level API to have:
- Be able to pass a `WebSocket` constructor optionally: Desktop chrome code doesn't expose `WebSocket`, however we have `Services.appShell.hiddenDOMWindow.WebSocket` :)
- Provide a way to extract `channelId` from the instance.

**Comment by rfk** [comment]
The above is premised on making the `PairingChannel` abstraction the preferred public API; currently it's in the "demo" directory.

**Comment by eoger** [comment]
Looking at our prior art, here's what I'm proposing:

```
class PairingChannel {
  static async create(listener: PairingChannelListener, [window]: {WebSocket, crypto}) -> Self
  static async connect(channelId: String, channelKey: UInt8Array, listener: PairingChannelListener, [window]: {WebSocket, crypto}) -> Self
  get closed() -> Bool
  get channelId() -> String // Same as channel server
  get channelKey() -> UInt8Array
  send(cleartext: Uint8Array)
  close()
}

class PairingChannelListener {
  async onMessage()
  async onClose()
  async onError()
}
```

**Comment by rfk** [comment]
> class PairingChannelListener

An alternative would be to implement a websocket-like `EventTarget` interface to which the calling code can subscribe using `addEventListener` and friends; do you have a strong preference for passing in a listener object rather than offering the `EventTarget` API?

**Comment by rfk** [comment]
Apart from that, this seems broadly workable to me, 👍

**Comment by eoger** [comment]
> `addEventListener`

Good idea, I'm ok with both!

**Comment by rfk** [comment]
I think I'd lightly prefer the `EventTarget.addEventListener` approach because it would feel more like "this is a websocket with extra features"; we'd have to be careful about race conditions though, and avoid the potential for lost messages in between resolving the promise from `create` and attaching the event listeners.

**Comment by rfk** [comment]
👍  we did this and it worked out well to parallelize development
