### ISSUE TITLE
Make the transpiled bundle smaller

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-pairing-channel#35]
We currently publish a transpiled bundle that uses babel's regenerator runtime to translate async/await, making it a pretty hefty bundle.  That should be fine to start, but we have previously discussed options for reducing the bundle size, e.g. by using a less general transpilation that converts async/await into promises.  I don't know how urgently we want to do that, but figured I'd file an issue to track it.

**Comment by shane-tomlinson** [comment]
How big are we talking?

**Comment by shane-tomlinson** [comment]
> How big are we talking?

250KB, it's not the end of the world, but remember this is being loaded on mobile devices.

**Comment by rfk** [comment]
Given the issue is now 2 years old, I think it's clear that we're not motivated to do this :-/
