### ISSUE TITLE
WebChannel error: TypeError: flow.finalize is not a function

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-pairing-channel#48]
WebChannel error: TypeError: flow.finalize is not a function

Found in https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/5628709/events/c3c5515c504540948c55b2008cf4aeee/

We should file this in Bugzilla or something.

**Comment by rfk** [comment]
I'm not seeing any instances of this in the latest sentry, going to close it out
